### PR TITLE
Updated Edge2Edge Meter to ElectricityMeter Nature

### PR DESCRIPTION
**Pull request by Sn0w3y**

### CODE REVIEW

**Comment by Sn0w3y** [comment]
Sorry for the extended PR (it includes the latest Updates from the main Repo)

**Comment by clehne** [comment]
@Sn0w3y Thanks for your contribution.  
@tsicking Could you please do a review of this updated source. When fine, either we or @Sn0w3y can open a new PR against the official repository.

**Comment by Sn0w3y** [comment]
some news on this topic @clehne @tsicking  ? :)

**Comment by sfeilmeier** [comment]
FYI: this was merged upstream in https://github.com/OpenEMS/openems/pull/2621

**Pull request closed without merging**
